[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.default.rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
optimism = "${OPT_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
