[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.default.rpc_endpoints]
optimism = "${OPT_RPC_URL}"
mainnet = "${ETH_RPC_URL}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
