[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./script/input/"},
    { access = "read-write", path = "./script/output/"},
    { access = "read", path = "./out/"}
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
